/**
 * Screen 7 — outputs: BOM, BOQ, Pricing, Quotation and execution drawings, generated by the API's engines for this
 * exact design version. The UI shows what the API returns; it computes no quantity, price or total.
 * FOR_PRODUCTION is offered only for an APPROVED / LOCKED version without BLOCKERs (the API refuses it otherwise too).
 */
import { useState } from "react";
import type { ScreenProps } from "../App";
import type { Schemas } from "../api/client";
import { api, idempotency, must, versionWithEtag } from "../api/client";
import { bomTableRows } from "../bomTable";
import { inr } from "../geometry";
import { Action, Badge, ErrorBox, Field, Section, useLoad } from "../ui";

type Purpose = "PRELIMINARY" | "FOR_REVIEW" | "FOR_PRODUCTION";
type Kind = Schemas["SnapshotEnvelope"]["kind"];
type Generated =
  | { readonly status: "AVAILABLE"; readonly reused: boolean; readonly snapshot: { readonly id: string; readonly kind: string } }
  | { readonly status: "UNAVAILABLE"; readonly kind: string; readonly blockers: readonly { readonly code: string; readonly message: string }[] };

export async function latestCommercial(type: "pricing_standard" | "quotation_policy"): Promise<string | null> {
  const r = await must(api.GET("/api/v1/reference-data/{type}/versions", { params: { path: { type }, query: { status: "APPROVED,LOCKED", limit: 100 } } }));
  return [...r.items].sort((a, b) => b.versionNumber - a.versionNumber)[0]?.id ?? null;
}

export async function snapshotOf(kind: Kind, snapshotId: string): Promise<Schemas["Snapshot"]> {
  const p = { params: { path: { snapshotId } } };
  switch (kind) {
    case "BOM": return must(api.GET("/api/v1/bom-snapshots/{snapshotId}", p));
    case "BOQ": return must(api.GET("/api/v1/boq-snapshots/{snapshotId}", p));
    case "PRICING": return must(api.GET("/api/v1/pricing-snapshots/{snapshotId}", p));
    case "QUOTATION": return must(api.GET("/api/v1/quotation-snapshots/{snapshotId}", p));
    case "DRAWING": return must(api.GET("/api/v1/drawing-snapshots/{snapshotId}", p));
  }
}

export function OutputsScreen({ sel }: ScreenProps) {
  const versionId = sel.versionId ?? "";
  const [n, setN] = useState(0);
  const graph = useLoad(() => must(api.GET("/api/v1/design-versions/{versionId}/outputs", { params: { path: { versionId } } })), `outputs:${versionId}:${String(n)}`);
  const version = useLoad(() => versionWithEtag(versionId), `oversion:${versionId}`);
  const model = useLoad(() => must(api.GET("/api/v1/design-versions/{versionId}/model", { params: { path: { versionId } } })), `omodel:${versionId}`);
  const [purpose, setPurpose] = useState<Purpose>("PRELIMINARY");
  const [drawingNumber, setDrawingNumber] = useState("");
  const [revision, setRevision] = useState("A");
  const [result, setResult] = useState<Generated | null>(null);
  const [open, setOpen] = useState<Schemas["Snapshot"] | null>(null);
  const status = version.data?.version.status;
  const blockers = model.data?.validation.counts.BLOCKER ?? 1;
  const productionAllowed = (status === "APPROVED" || status === "LOCKED") && blockers === 0;
  const done = (r: Generated) => { setResult(r); setN((x) => x + 1); };
  const header = () => ({ "Idempotency-Key": idempotency() });
  const path = { versionId };
  const commercial = async () => {
    const pricingStandardVersionId = await latestCommercial("pricing_standard");
    if (pricingStandardVersionId === null) throw new Error("No APPROVED PricingStandard: pricing is not possible (see docs/PILOT-BLOCKERS.md).");
    return pricingStandardVersionId;
  };

  return (
    <>
      <ErrorBox error={graph.error ?? version.error ?? model.error} />
      <Section title="Generate">
        <div className="row">
          <Field label="Purpose">
            <select value={purpose} onChange={(e) => { setPurpose(e.target.value as Purpose); }}>
              <option value="PRELIMINARY">PRELIMINARY</option>
              <option value="FOR_REVIEW">FOR_REVIEW</option>
              <option value="FOR_PRODUCTION" disabled={!productionAllowed}>FOR_PRODUCTION{productionAllowed ? "" : " (needs an APPROVED / LOCKED version, 0 BLOCKER)"}</option>
            </select>
          </Field>
          <Field label="Drawing number" hint="A–Z, 0–9, -"><input value={drawingNumber} onChange={(e) => { setDrawingNumber(e.target.value.toUpperCase()); }} placeholder="e.g. KIT-01" /></Field>
          <Field label="Revision"><input className="num" value={revision} onChange={(e) => { setRevision(e.target.value.toUpperCase()); }} /></Field>
        </div>
        <div className="row">
          <Action label="BOM" run={async () => { done(await must(api.POST("/api/v1/design-versions/{versionId}/bom-snapshots", { params: { path, header: header() }, body: { purpose } }))); }} />
          <Action label="BOQ" run={async () => { done(await must(api.POST("/api/v1/design-versions/{versionId}/boq-snapshots", { params: { path, header: header() }, body: { purpose } }))); }} />
          <Action label="Pricing" run={async () => { done(await must(api.POST("/api/v1/design-versions/{versionId}/pricing-snapshots", { params: { path, header: header() }, body: { purpose, pricingStandardVersionId: await commercial() } }))); }} />
          <Action label="Quotation" run={async () => {
            const pricingStandardVersionId = await commercial();
            const quotationPolicyVersionId = await latestCommercial("quotation_policy");
            if (quotationPolicyVersionId === null) throw new Error("No APPROVED QuotationPolicy: a quotation is not possible (see docs/PILOT-BLOCKERS.md).");
            done(await must(api.POST("/api/v1/design-versions/{versionId}/quotation-snapshots", { params: { path, header: header() }, body: { purpose, pricingStandardVersionId, quotationPolicyVersionId } })));
          }} />
          <Action label="Drawing: wall A elevation" disabled={drawingNumber === ""} run={async () => { done(await must(api.POST("/api/v1/design-versions/{versionId}/drawing-snapshots", { params: { path, header: header() }, body: { purpose, drawingType: "WALL_INTERNAL_ELEVATION", wallId: "A", drawingNumber: `${drawingNumber}-A`, drawingRevision: revision } }))); }} />
          <Action label="Drawing: panel schedule" disabled={drawingNumber === ""} run={async () => { done(await must(api.POST("/api/v1/design-versions/{versionId}/drawing-snapshots", { params: { path, header: header() }, body: { purpose, drawingType: "ROOM_PANEL_SCHEDULE", drawingNumber: `${drawingNumber}-PS`, drawingRevision: revision } }))); }} />
        </div>
        {result?.status === "UNAVAILABLE" && (
          <div className="error">{result.kind} not available: {result.blockers.map((b) => `${b.code}: ${b.message}`).join(" · ")}</div>
        )}
        {result?.status === "AVAILABLE" && <p><Badge tone="ok">{result.snapshot.kind}</Badge> {result.reused ? "already existed for these exact inputs (reused)" : "generated"} — <code>{result.snapshot.id}</code></p>}
      </Section>
      <Section title="Outputs of this version">
        <table>
          <thead><tr><th>Kind</th><th>Purpose</th><th>BLOCKER</th><th>WARNING</th><th>Issue</th><th>Content</th><th /></tr></thead>
          <tbody>
            {(graph.data?.nodes ?? []).map((s) => (
              <tr key={s.id}>
                <td>{s.kind}</td><td>{s.purpose}</td>
                <td>{s.blockerCount > 0 ? <Badge tone="bad">{s.blockerCount}</Badge> : "0"}</td><td>{s.warningCount}</td>
                <td>{s.qualifiesForIssue ? <Badge tone="ok">issuable</Badge> : "—"}</td>
                <td><code>{s.contentHash.slice(7, 19)}</code></td>
                <td><Action label="View" run={async () => { setOpen(await snapshotOf(s.kind, s.id)); }} /></td>
              </tr>
            ))}
            {graph.data?.nodes.length === 0 && <tr><td colSpan={7}>Nothing generated yet.</td></tr>}
          </tbody>
        </table>
        {(graph.data?.hiddenKinds.length ?? 0) > 0 && <p>Not visible with your role: {graph.data?.hiddenKinds.join(", ")}.</p>}
      </Section>
      {open !== null && <SnapshotView s={open} objectCodes={model.data?.objects.map((o) => o.objectCode) ?? []} />}
    </>
  );
}

/** The exact quotation Sales will issue (Sales may issue but not read cost outputs): id, reviewed content hash, commercial versions. */
export interface HandOver { readonly id: string; readonly contentHash: string; readonly pricingStandardVersionId: string; readonly quotationPolicyVersionId: string }
export const handOverCode = (h: HandOver): string => btoa(JSON.stringify(h)).replace(/=+$/, "");
export function parseHandOver(code: string): HandOver {
  const v = JSON.parse(atob(code.trim())) as Partial<HandOver>;
  if (typeof v.id !== "string" || typeof v.contentHash !== "string" || typeof v.pricingStandardVersionId !== "string" || typeof v.quotationPolicyVersionId !== "string") throw new Error("Not a quotation hand-over code.");
  return { id: v.id, contentHash: v.contentHash, pricingStandardVersionId: v.pricingStandardVersionId, quotationPolicyVersionId: v.quotationPolicyVersionId };
}

/** Headline figures of a snapshot as the API returned them, its full payload, and — P2, BOM only — a readable
 * table (presentation only: every figure here is exactly what `roomBom`/`packages/types/src/bom.ts`'s `BOMItem`
 * already computed, just laid out for a designer instead of the raw JSON collapsed below it). `objectCodes`
 * (needed only to attribute a BOM line to the cabinet it belongs to) is optional — omit it, or pass `[]`, where
 * the design's objects aren't already loaded; every other snapshot kind ignores it entirely. */
export function SnapshotView({ s, objectCodes = [] }: { readonly s: Schemas["Snapshot"]; readonly objectCodes?: readonly string[] }) {
  const p = (s.payload ?? {}) as Record<string, unknown>;
  const totals = (p.totals ?? {}) as Record<string, unknown>;
  const bomRows = s.kind === "BOM" ? bomTableRows(p, objectCodes) : [];
  return (
    <Section title={`${s.kind} ${s.purpose} — ${s.id}`}>
      <p>Design version <code>{s.designVersionId}</code> ({s.designVersionStatus}) · input <code>{s.input.hash.slice(0, 19)}…</code> · engine {s.engine.name} {s.engine.version} · {s.blockerCount} BLOCKER, {s.warningCount} WARNING</p>
      {(s.kind === "PRICING" || s.kind === "QUOTATION") && (
        <table><tbody>{Object.entries(totals).map(([k, v]) => <tr key={k}><td>{k}</td><td>{typeof v === "number" && /paise|total|amount|tax|price|cost/i.test(k) ? inr(v) : JSON.stringify(v)}</td></tr>)}</tbody></table>
      )}
      {s.kind === "QUOTATION" && s.purpose === "FOR_PRODUCTION" && s.commercial !== null && s.commercial.quotationPolicyVersionId !== null && (
        <p>Hand-over code for Sales (issues this exact quotation): <code className="handover">{handOverCode({ id: s.id, contentHash: s.contentHash, pricingStandardVersionId: s.commercial.pricingStandardVersionId, quotationPolicyVersionId: s.commercial.quotationPolicyVersionId })}</code></p>
      )}
      {s.kind === "BOM" && (
        bomRows.length === 0 ? <p>No BOM lines.</p> : (
          <table className="bom-table">
            <thead><tr><th>Cabinet</th><th>Component</th><th>Qty</th><th>Material</th><th>Finish</th><th>Hardware</th></tr></thead>
            <tbody>
              {bomRows.map((r, i) => <tr key={i}><td>{r.cabinet}</td><td>{r.component}</td><td>{r.qty}</td><td>{r.material}</td><td>{r.finish}</td><td>{r.hardware}</td></tr>)}
            </tbody>
          </table>
        )
      )}
      <details><summary>Full payload (as stored)</summary><pre>{JSON.stringify(p, null, 2)}</pre></details>
    </Section>
  );
}
