/**
 * Deterministic, version-independent description of the design_os schema, built from the system catalogs
 * (no pg_dump, so client and server versions never matter). Committed as database/schema/design_os.schema.txt;
 * the drift test fails if the migrations and the committed snapshot disagree.
 */
import type pg from "pg";

const QUERIES: readonly (readonly [string, string])[] = [
  ["column", `SELECT c.relname || '.' || a.attname || ' ' || format_type(a.atttypid, a.atttypmod) || CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END || coalesce(' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid), '')
      FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid JOIN pg_namespace n ON n.oid = c.relnamespace LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
      WHERE n.nspname = 'design_os' AND c.relkind = 'r' AND a.attnum > 0 AND NOT a.attisdropped ORDER BY c.relname, a.attnum`],
  ["constraint", `SELECT conrelid::regclass::text || ' ' || conname || ' ' || pg_get_constraintdef(oid) FROM pg_constraint WHERE connamespace = 'design_os'::regnamespace AND conrelid <> 0 ORDER BY 1`],
  ["index", `SELECT pg_get_indexdef(indexrelid) FROM pg_index i JOIN pg_class c ON c.oid = i.indrelid WHERE c.relnamespace = 'design_os'::regnamespace ORDER BY 1`],
  ["trigger", `SELECT pg_get_triggerdef(oid) FROM pg_trigger WHERE NOT tgisinternal AND tgrelid IN (SELECT oid FROM pg_class WHERE relnamespace = 'design_os'::regnamespace) ORDER BY 1`],
  ["function", `SELECT proname || '(' || pg_get_function_identity_arguments(oid) || ') -> ' || pg_get_function_result(oid) || CASE WHEN prosecdef THEN ' SECURITY DEFINER' ELSE '' END
      || coalesce(' ' || array_to_string(proconfig, ','), '') || ' owner=' || proowner::regrole::text || ' src=' || md5(prosrc) FROM pg_proc WHERE pronamespace = 'design_os'::regnamespace ORDER BY 1`],
  ["enum", `SELECT t.typname || ' ' || string_agg(e.enumlabel, ',' ORDER BY e.enumsortorder) FROM pg_type t JOIN pg_enum e ON e.enumtypid = t.oid WHERE t.typnamespace = 'design_os'::regnamespace GROUP BY t.typname ORDER BY 1`],
  ["table", `SELECT relname || ' owner=' || relowner::regrole::text || ' rls=' || relrowsecurity FROM pg_class WHERE relnamespace = 'design_os'::regnamespace AND relkind = 'r' ORDER BY 1`],
  ["policy", `SELECT tablename || ' ' || policyname || ' ' || cmd || ' ' || array_to_string(roles, ',') || ' USING ' || coalesce(qual, '-') || ' CHECK ' || coalesce(with_check, '-') FROM pg_policies WHERE schemaname = 'design_os' ORDER BY 1`],
  ["grant", `SELECT grantee || ' ' || table_name || ' ' || privilege_type FROM information_schema.role_table_grants WHERE table_schema = 'design_os' AND grantee NOT IN ('design_os_owner') ORDER BY 1`],
  ["column_grant", `SELECT grantee || ' ' || table_name || '.' || column_name || ' ' || privilege_type FROM information_schema.column_privileges
      WHERE table_schema = 'design_os' AND grantee = 'design_os_api' AND privilege_type = 'UPDATE' ORDER BY 1`],
  ["routine_grant", `SELECT grantee || ' ' || routine_name || ' ' || privilege_type FROM information_schema.routine_privileges WHERE routine_schema = 'design_os' AND grantee NOT IN ('design_os_owner') ORDER BY 1`],
  ["registry", `SELECT subject_type || ' ' || version_table::text || ' ' || entity_table::text || ' ' || author_action || ' ' || approve_action FROM design_os.versioned_table ORDER BY 1`],
];

export async function schemaSnapshot(client: pg.Client): Promise<string> {
  await client.query("SET search_path = pg_catalog");
  const lines: string[] = ["# design_os schema snapshot (generated by tests/db; do not edit by hand — run `pnpm db:schema:update`)"];
  for (const [section, sql] of QUERIES) {
    const r = await client.query<Record<string, string>>(sql);
    const values = r.rows.map((row) => (Object.values(row)[0] ?? "").replace(/\s+/g, " "));
    // Order independently of the server's collation (CI and local clusters differ): code-point order.
    // Columns keep their attribute order within each table (stable sort on the table name only).
    const key = section === "column" ? (v: string) => v.slice(0, v.indexOf(".")) : (v: string) => v;
    values.sort((x, y) => (key(x) < key(y) ? -1 : key(x) > key(y) ? 1 : 0));
    for (const v of values) lines.push(`${section}: ${v}`);
  }
  await client.query("RESET search_path");
  return `${lines.join("\n")}\n`;
}
